version: '3.5'

services:
  django:
    build: .
    user: app
    command: test
    volumes:
      - .:/app
    environment:
      IPYTHONDIR: /app/.ipython
      HISTFILE: /app/.bash_history
    restart: "no"
